# Generated by Django 5.1.3 on 2025-03-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frontend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('discount', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
